site_name: RISC-V Steel Documentation
site_author: Rafael Calcada
site_description: RISC-V Steel is a free and open collection of RISC-V IP that is simple, robust and easy to use.
repo_url: https://github.com/riscv-steel/riscv-steel
edit_uri: edit/main/docs/source/
markdown_extensions:
    - abbr
    - attr_list
    - md_in_html
    - tables
    - footnotes
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
theme:
    name: material
    logo: images/rvsteel_logo_circle.svg
    favicon: images/rvsteel_logo_circle.svg
    highlightjs: true
    palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.expand
        - navigation.instant
        - navigation.instant.progress
        - content.code.copy
        - content.code.select
extra:
    analytics:
        provider: google
        property: G-6380GKCWC3
extra_css: [extra.css]
plugins:
    - search
docs_dir: source/
remote_branch: docs
copyright: Copyright (c) RISC-V Steel contributors
nav:
    - Homepage: 'index.md'    
    - User Guide: 'userguide.md'
    - Hardware Docs:
        - Microcontroller: 'hardware/mcu.md'
        - Processor Core: 'hardware/core.md'
    - LibSteel Docs:
        - Introduction: 'libsteel.md'
        - UART Controller: 'libsteel/uart.md'
    - Examples:
        - Hello World: 'examples/helloworld.md'
        - FreeRTOS: 'examples/freertos.md'